#constant_warmup: false - Example for boolean

iam_filepath: ./IAM/
image_directory: ./IAM/AllImages/
train_label_directory: ./IAM/train_labels.txt
test_label_directory: ./IAM/test_labels.txt
pretrained_model: microsoft/trocr-base-handwritten
pretrained_processor: microsoft/trocr-base-handwritten
token_id: 0
num_epochs: 5000
batch_size: 12
learning_rate: 5e-5
warmup_steps: 15000
image_height: 384
image_width: 384
use_learned_embeddings: false
