#constant_warmup: false - Example for boolean
iam_filepath: /grphome/grp_handwriting/TrOCRv2/IAM/
image_directory: /grphome/grp_handwriting/TrOCRv2/IAM/AllImages/
train_label_directory: /grphome/grp_handwriting/TrOCRv2/IAM/train_labels.txt
test_label_directory: /grphome/grp_handwriting/TrOCRv2/IAM/test_labels.txt
load_model: false
load_model_path:
pretrained_model: microsoft/trocr-base-handwritten
pretrained_processor: microsoft/trocr-base-handwritten
token_id: 0
num_epochs: 10
batch_size: 40
learning_rate: 5e-5
warmup_steps: 15000
image_height: 384
image_width: 384
use_learned_embeddings: false
num_workers: 16
synth_epochs: 8
num_synth_images: 500
synth_directory: /home/tarch/datasets/synthetic/lines/english/
synth_labels: /home/tarch/datasets/synthetic/lines/english_labels/text_labels_correct_headers.npy